crds:
  migration:
    enabled: false

admissionController:
  serviceMonitor:
    enabled: false
  metering:
    disabled: false

grafana: # you need grafana-crd, so we use cm in a separate step
  enabled: false
  grafanaDashboard:
    create: false